apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
  name: hello-skaffold-gke
description: Delivery Pipeline for a sample app
serialPipeline:
  stages:
    - targetId: dev
    - targetId: prod

---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: dev
description: sample dev cluster
gke:
  cluster: projects/biju-altostrat-demo/locations/us-west1-a/clusters/standard-cluster-1

---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: prod
description: sample prod cluster
requireApproval: true
gke:
  cluster: projects/biju-altostrat-demo/locations/us-west1-a/clusters/standard-cluster-prod