apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: hello-skaffold-gke
description: Delivery Pipeline for a sample java app
serialPipeline:
  stages:
    - targetId: dev
      # strategy:
      #   canary:
      #     runtimeConfig:
      #       kubernetes:
      #         serviceNetworking:
      #           service: "hello-skaffold-gke-service"
      #           deployment: "hello-skaffold-gke-deployment"
      #     canaryDeployment:
      #       percentages: [15]
      #       verify: false
    - targetId: prod

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: A Dev cluster
gke:
  cluster: projects/biju-altostrat-demo/locations/us-west1/clusters/demo-cluster

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
description: A Prod cluster
requireApproval: true
gke:
  cluster: projects/biju-altostrat-demo/locations/us-west1/clusters/demo-cluster