apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
  name: hello-skaffold-gke
description: Delivery Pipeline for a sample app
serialPipeline:
  stages:
    - targetId: dev
      profiles: []
---

apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: dev
description: sample dev cluster
gke:
  cluster: projects/biju-altostrat-demo/locations/us-west1/clusters/sample-standard-cluster-1