steps:
  - name: eclipse-temurin:17.0.6_10-jdk
    id: test
    entrypoint: "/bin/bash"
    args:
      - '-c'
      - |-
        ./gradlew check
  - name: "us-west1-docker.pkg.dev/$PROJECT_ID/sample-repo/skaffold:latest"
    id: build-image
    entrypoint: "/bin/bash"
    args:
      - '-c'
      - |-
        set -x
        # skaffold build --interactive=false --default-repo=us-west1-docker.pkg.dev/$PROJECT_ID/sample-repo --file-output artifacts.json
        ./gradlew jibDockerBuild --image us-west1-docker.pkg.dev/$PROJECT_ID/sample-repo/hello-skaffold-gke:$SHORT_SHA
        docker image inspect "us-west1-docker.pkg.dev/$PROJECT_ID/sample-repo/hello-skaffold-gke:$SHORT_SHA" --format '{{index .RepoDigests 0}}' > image-digest.txt

  - name: 'gcr.io/cloud-builders/gcloud'
    id: trigger-deploy
    entrypoint: /bin/bash
    args:
      - '-c'
      - |-
        set -x
        gcloud beta deploy releases create release-$SHORT_SHA --delivery-pipeline hello-skaffold-gke --region us-west1 --images "hello-skaffold-gke=$(cat image-digest.txt)"

  # - name: 'gcr.io/cloud-builders/gcloud'
  #   id: trigger-deploy
  #   args: [ "beta", "deploy", "releases",  "create",  "release-$SHORT_SHA", "--delivery-pipeline",  "hello-skaffold-gke", "--region", "us-west1", "--build-artifacts", "artifacts.json" ]

images:
- us-west1-docker.pkg.dev/$PROJECT_ID/sample-repo/hello-skaffold-gke:$SHORT_SHA
options:
    requestedVerifyOption: VERIFIED
