steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', "-f", "Dockerfile-java17",
      '-t', "us-west1-docker.pkg.dev/$PROJECT_ID/sample-repo/skaffold:$SHORT_SHA",
      '-t', "us-west1-docker.pkg.dev/$PROJECT_ID/sample-repo/skaffold:latest",'.'
    ]
images: [
  "us-west1-docker.pkg.dev/$PROJECT_ID/sample-repo/skaffold:$SHORT_SHA",
  "us-west1-docker.pkg.dev/$PROJECT_ID/sample-repo/skaffold:latest"
]
