management:
  endpoint:
    health:
      enabled: true
      show-details: always
      probes:
        enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"